import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'VortexGlide',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta
          name="google-site-verification"
          content="PiL2cPridcHsMn4gPwxvPMx2jrwJSA8bYdTTrw4JpOI"
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
